[package]
name = "todomvc-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zi = "0.3.2"
zi-term = "0.3.2"
